"""add_password_to_owner

Revision ID: 1426f57daf30
Revises: cebe618d6ffc
Create Date: 2026-02-16 16:50:00.348128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# down_revision set to None because cebe618d6ffc was removed; this is now the base.
revision: str = '1426f57daf30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('password_hash', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'password_hash')
    # ### end Alembic commands ###
