"""inspector table updated

Revision ID: 1a054beb8a0e
Revises: 
Create Date: 2026-01-05 11:41:25.529346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a054beb8a0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspector', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Boolean(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspector', 'status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###

