"""database updated

Revision ID: 646fc028dd27
Revises: 
Create Date: 2026-02-17 15:20:46.114922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646fc028dd27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'phone',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('inspector', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('user_type', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('notifications', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_notifications_owner_id'), 'notifications', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'owners', ['owner_id'], ['id'])
    op.add_column('owners', sa.Column('password_hash', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'password_hash')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_owner_id'), table_name='notifications')
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('notifications', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'user_type')
    op.drop_column('notifications', 'user_id')
    op.drop_column('inspector', 'password_hash')
    op.alter_column('admins', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###

