"""evidence table updated

Revision ID: dd2a2e6a9afc
Revises: 
Create Date: 2026-01-07 16:31:14.851601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2a2e6a9afc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_evidence_inspection_id'), 'evidence', ['inspection_id'], unique=False)
    op.create_foreign_key(None, 'evidence', 'inspection', ['inspection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_inspection_id'), table_name='evidence')
    # ### end Alembic commands ###

